#!/usr/bin/env python

import os, sys, itertools

kind = sys.argv[2]

def mp(file):
  words = set()
  for w in (w.rstrip() for w in open(file)):
     if w:
       words.add(w)
  words.add('NULL')
  return words

swords = mp(sys.argv[1])
twords = mp(sys.argv[2])

for v in (ln.rstrip('\n').split() for ln in sys.stdin):
  if (v[0] in swords) and (v[1] in twords):
    print ' '.join(v)

