#!/usr/bin/env perl

use FindBin qw($Bin);
use lib "$Bin/..";
use NLPRules qw(extract_feat_safe feature_spec);

while (<>) {
    chomp;
    $rule = $_;
    $rule =~ s/\s+$//;
    %v = feature_spec(extract_feat_safe($rule));
    print "$v{id}\t$rule\n";
}
