#!/usr/bin/env python
import sys
import itertools
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-w','--width', type=int, default=20)
args = parser.parse_args()
rep = args.width

def inp():
    for line in sys.stdin:
        yield line.rstrip('\n').split('\t')
	
for p,seq in itertools.groupby(inp(),lambda x : x[0:2]):
    s = []
    for ss in seq:
        s += ss[2:]
    if rep <= 0:
        print '\t'.join(p + s)
    else:
        for x in xrange(rep):
             print '\t'.join(p + ["%s" % x] + s)
 
    
