#!/usr/bin/env python
import sys
try:
    for line in sys.stdin:
        v = line.rstrip('\n').split('\t')
        print '\t'.join(v[3:4] + v[0:2] + v[4:])
except:
    print >> sys.stderr, 'failed to process:',line
    raise

