#!/usr/bin/env python

import sys
import getopt



inverse = False
opts, args = getopt.getopt(sys.argv[1:], "i")

for o, a in opts:
    if o == "-i":
        inverse = True

def surface(s):
    if s[0] == '"':
        return s[1:-1]
    else:
        return False
    

for line in sys.stdin:
    id,fstr,estr,astr = line.rstrip('\n').split('\t')
    cid = str(int(id) % 20)
    align = [tuple(int(i) for i in s.split('-',1)) for s in astr.split()]
    frhs = [surface(w) for w in fstr.split()]
    erhs = [surface(w) for w in estr.split()]

    if inverse:
        frhs, erhs = erhs, frhs
        align = [(ei, fi) for (fi, ei) in align]
        
    ealign = [[] for ei in xrange(len(erhs))]
    for fi,ei in align:
        ealign[ei].append(frhs[fi])

    for ei, e in enumerate(erhs):
        if not e: continue
        eis = str(ei)
        if len(ealign[ei]) > 0:
            for f in ealign[ei]:
                print '\t'.join((f,e,cid,id,eis))
                print '\t'.join((f,'*lambda*',cid,id,eis))
        else:
            print '\t'.join(("NULL",e,cid,id,eis))
