#!/usr/bin/env python

import sys, getopt, collections

# input: fwords ewords align

inverse = False # P(f|e)
opts, args = getopt.getopt(sys.argv[1:], "i")
for o, a in opts:
    if o == "-i":
        inverse = True

for line in sys.stdin:
    fields = line.rstrip("\n").split("\t")
    fwords, ewords, align, weights = fields
    fwords = fwords.split()
    ewords = ewords.split()
    align = [tuple(int(i) for i in a.split("-")) for a in align.split()]
    weights = [float(weight) for weight in weights.split()]
    if inverse:
        fwords, ewords = ewords, fwords
        align = [(fi,ei) for (ei,fi) in align]

    fertility = collections.defaultdict(int)
    for fi,ei in align:
        fertility[ei] += 1

    for fi,ei in align:
        print "* %s\t%s\t%s" % (fwords[fi], ewords[ei], ' '.join(str(weight/fertility[ei]) for weight in weights))
    for ei in xrange(len(ewords)):
        if fertility[ei] == 0:
            print "* NULL\t%s\t%s" % (ewords[ei], ' '.join(str(weight) for weight in weights))
