#!/usr/bin/env python

import sys, math

unk = str(math.exp(float(sys.argv[1])))

for line in sys.stdin:
    d = line.split('\t')
    if len(d) == 3:
        d.append(unk)
    assert(len(d) == 4)
    p,s,rule,scr = d
    print '\t'.join([rule,p,s,scr])
