#!/usr/bin/env python

import sys

for line in sys.stdin:
    line = line.strip()
    fields = line.split('\t')
    rule = fields[0]
    print rule + " ### " + ' '.join(field for field in fields[1:])
    
