#!/usr/bin/env python

import sys

for line in sys.stdin:
    line = line.strip()
    fields = line.split('\t')
    rule = fields[0]
    id = fields[1]
    print rule + " ### id=" + id + ' ' + ' '.join(field for field in fields[2:])
    
