#!/usr/bin/env python
import cfg, os, sys, argparse
import inputs

curr = os.path.dirname(__file__)
parser = inputs.parser
nkparser = argparse.ArgumentParser()

for p in [parser,nkparser]:
    p.add_argument( '-n', '--nocleanup' \
                  , help='do not toss the temporary $tmpdir'
                  , action='store_false'
                  , dest='cleanup'
                  )
d = cfg.parse_args(parser,modeldir=True)
vals,remain = nkparser.parse_known_args()
nk=''

if not d.cleanup:
    nk += ' --nocleanup'

cfg.execute( d, '$curr/runinputs ' + ' '.join('"'+x+'"' for x in remain)
           , curr=curr )
cfg.execute( d, '$curr/runextras -n -o "$outdir" -t "$tmpdir"'
           , outdir=d.outdir
           , tmpdir=d.tmpdir
           , curr=curr )
cfg.execute( d, '$curr/runfinal -o "$outdir" -t "$tmpdir"$nk'
           , outdir=d.outdir
           , tmpdir=d.tmpdir
           , curr=curr
           , nk=nk )

