#!/usr/bin/env python

import itertools
import cfg
import argparse
import sys
import os.path
import re


parser = argparse.ArgumentParser()
parser.add_argument('extname')
parser.add_argument('flatfile')
d = cfg.parse_args(parser)

hp = d.hadoop

ffile = os.path.basename(d.flatfile)
hp.put(d.flatfile,ffile)
#mapper = r"sed -e 's/\(.* sid=\([0-9]*\).*\)/\2\t\1/'"
#mapper += " | sed -e 's/ sentid=[-0-9]*//'"
hp.mapreduce(mapper='cat', input=ffile, output='part.'+d.extname)
hp.remove(ffile)
