#!/usr/bin/env python

# produce count distribution of head word and symbol for variable head word/pos tags  for rules

import sys, itertools, optparse, math
from collections import defaultdict


def keyval(input):
    for line in input:
        line = line.strip()
        yield line.split('\t')

def reducer(input):
    # split on symbol + head
    for keylen, records in itertools.groupby(keyval(input), lambda x: x[:2]):
        sum = reduce(lambda x, y: x+int(y[2]), records, 0)
        sys.stdout.write('\t'.join(keylen+[str(sum),])+"\n")

if __name__ == "__main__":
    desc = optparse.OptionParser()
    opts,ignore = desc.parse_args(sys.argv[1:])

    reducer(sys.stdin)
        

