#!/usr/bin/env python

import sys, os

wordfile = open(sys.argv[1])
tagfile = open(sys.argv[2])

for t,hw,p in (line.rstrip('\n').split() for line in wordfile):
    print "tag %s\t0" % t
    print "target %s\t0" % hw

for t,ht,p in (line.rstrip('\n').split() for line in tagfile):
    print "tag %s\t0" % t
    print "tag %s\t0" % ht
