#!/usr/bin/env python

import sys
import re

lhsre = re.compile(r'^([^()]*)')

for line in sys.stdin:
    line = line.strip()
    fields = line.split('\t')
    rule = fields[0]
    lhs = lhsre.match(rule).group(1)
    id = fields[1]
    hwpos = fields[2]
    sig = fields[3]
    
    print sig + '\t' + id + '\t' + lhs + '\t' + '\t'.join(field for field in fields[4:])
