#!/usr/bin/env python
import sys
from itertools import groupby

def data(lines):
    for line in lines:
        v = line.strip().split('\t')
        yield (v[0], v[2].split(),v[4],v[-1])

for k,datum in groupby(data(sys.stdin), lambda x : x[0]):
    for d in datum:
        ignore,src,rid,rule = d 
        print "%(rule)s lineRawID=%(id)s lineLength=%(len)s" % { 'rule':rule, 'id':rid, 'len':len(src) }

