#!/usr/bin/env python
import sys, pickle
from itertools import groupby

auxmap = pickle.load(open(sys.argv[1]))

def data(lines):
    for line in lines:
        v = line.strip().split('\t')
        yield (v[0], v[auxmap['weighted-count']], v[-1])

for k,datum in groupby(data(sys.stdin), lambda x : x[0]):
    for d in datum:
        ignore,t,r = d 
        print "%(r)s cwt={{{%(c)s}}}" % { 'r':r, 'c':t }

