#!/usr/bin/env python

from hadoop import Hadoop
from argparse import ArgumentParser
import cfg

parser = ArgumentParser()
args = cfg.parse_args(parser)
hp = args.hadoop

bindir = args.config['variables']['rhbin']

hp.mapreduce( mapper='%s/count_feature_mapper' % bindir
            , reducer='%s/count_feature_reducer' % bindir + r" -f '%key\tcount={{{%count}}}'"
            , input='rules' 
            , output='part.count' 
            )
