#!/usr/bin/env python

from hadoop import Hadoop
from argparse import ArgumentParser
import cfg

parser = ArgumentParser()
args = cfg.parse_args(parser)
hp = args.hadoop

bindir = args.config['variables']['rhbin']

hp.mapreduce( mapper='%s/rule_head_mapper' % bindir
            , reducer='%s/rule_head_reducer' % bindir
            , input='rules'
            , output='part.head-distributions' )

