#!/usr/bin/env python

from hadoop import Hadoop
from argparse import ArgumentParser
import cfg

parser = ArgumentParser()
parser.add_argument('field')
args = cfg.parse_args(parser)
hp = args.hadoop

bindir = args.config['variables']['rhbin']

hp.start()
hp.mapreduce( mapper = ('%s/max_feature_mapper ' % bindir) + args.field
            , reducer = '%s/max_feature_reducer' % bindir
            , combiner = '%s/max_feature_reducer -c' % bindir
            , input = 'rules'
            , output = 'part.' + args.field
            , sortkeys = 2
            , partitionkeys = 1 )
