#!/usr/bin/env python

# how many equivalent minimal rules make up this derivation?

import argparse
import cfg
import os.path
import sys

parser = argparse.ArgumentParser()
args = cfg.parse_args(parser)
bindir = args.config['variables']['rhbin']

fields = os.path.join(bindir, 'fields')+' 1 0'
count = os.path.join(bindir, 'count_feature_reducer')+r" --tokens -f '%key\tmincount=%count'"

hp = args.hadoop


hp.mapreduce( mapper = fields
              , sortkeys = 1
              , reducer = count
              , input  = 'idmap'
              , output = 'part.mincount'
            )
