#!/usr/bin/env python

from hadoop import Hadoop
from argparse import ArgumentParser
import cfg

parser = ArgumentParser()
parser.add_argument('field')
args = cfg.parse_args(parser)
hp = args.hadoop

bindir = args.config['variables']['rhbin']

hp.mapreduce( mapper = ('%s/max_feature_mapper %s' % (bindir,args.field))
            , reducer = '%s/set_reducer' % bindir
            , input = 'rules' 
            , output = 'part.' + args.field )
