#!/usr/bin/env python

import argparse
import cfg
import os.path

parser = argparse.ArgumentParser()
args = cfg.parse_args(parser)
hp = args.hadoop
#dir = os.path.dirname(os.path.dirname(__file__))
#scriptdir = os.path.abspath(os.path.join(dir,'scripts','syntax-mira','mira-features'))
scriptdir = args.config['variables']['rhsdir']
scriptdir = os.path.join(scriptdir,'syntax-mira','mira-features')

hp.mapreduce( mapper = os.path.join(scriptdir, 'single-level-rewrite.sh')
            , input = 'rules'
            , output = 'part.single-level-rewrite'
            )
