#!/usr/bin/env python

import cfg, argparse, os, sys, pickle
parser=argparse.ArgumentParser()

parser.add_argument('ext')
d = cfg.parse_args(parser)
hp = d.hadoop

bindir = d.config['variables']['rhbin']
tdir=os.path.join(d.scriptdir,'taglex')
ext = d.ext
part='part.lexmorph.nrm'
flag=''
if ext == 'inv':
    flag=' -i'
    part='part.lexmorph.inv'

auxmap = pickle.load(open(d.tmpdir + "/training.aux.map"))


if not hp.file_exists('training'):
    hp.put(os.path.join(d.tmpdir,'training'),'training')

hp.mapreduce( input='training'
            , output='data'
            , mapper=os.path.join(d.config['variables']['rhbin'],'mkdata') + ' ' + str(auxmap['weighted-count'])
            )
hp.mapreduce( input='data'
            , output='data.estem'
            , mapper=os.path.join(d.scriptdir,'mkdatastem')
            )
hp.mapreduce( input='data.estem'
            , output='data.f2estem'
            , mapper=os.path.join(bindir,'fields') + " 0 2 3 4"
            )
hp.mapreduce( input='data.estem'
            , output='data.estem2e'
            , mapper=os.path.join(bindir,'fields') + " 2 1 4"
            )
hp.remove('data')
hp.mapreduce( input='data.f2estem'
            , mapper=os.path.join(d.config['variables']['rhbin'],'count_align_weighted') + flag
            , reducer=os.path.join(d.config['variables']['rhbin'],'divide')
            , output='lex.f2estem.star'
            ) 
hp.mapreduce( input='lex.f2estem.star'
            , mapper=os.path.join(bindir,'fields') + r" -d ' \t' 1 2 3"
            , output='lex.f2estem'
            )
hp.mapreduce( input='data.estem2e'
            , mapper=os.path.join(d.config['variables']['rhbin'],'count_align_trivial_weighted') + flag
            , reducer=os.path.join(d.config['variables']['rhbin'],'divide')
            , output='lex.estem2e'
            )
#hp.getmerge('lex.estem2e',os.path.join(d.tmpdir,'lex.estem2e.'+ext))
#hp.getmerge('lex.f2estem',os.path.join(d.tmpdir,'lex.f2estem.'+ext))
if ext == 'inv':
    hp.mapreduce( input='lex.estem2e'
                , output='lex.estem2e.inverted'
                , mapper=os.path.join(bindir,'fields') + r" -d ' \t' 1 0 2"
                )
    cfg.execute( d
               , '$join lex.f2estem lex.estem2e.inverted -c $config -o lex.f2e.unsummed'
               , join=os.path.join(d.scriptdir,'join')
               , config=d.config_files
               )
    hp.mapreduce( input='lex.f2e.unsummed'
                , mapper=os.path.join(bindir,'fields') + " 3 1 4 2"
                , sortkeys=2
                , reducer=os.path.join(d.scriptdir,'compose_table')
                , output='lex.final' )
    hp.remove('lex.f2estem')
    hp.remove('lex.estem2e')
    hp.remove('lex.estem2e.inverted')
else:
    hp.mapreduce( input='lex.f2estem'
                , output='lex.f2estem.inverted'
                , mapper=os.path.join(bindir,'fields') + r" -d ' \t' 1 0 2"
                )
    cfg.execute( d
               , '$join lex.f2estem.inverted lex.estem2e -c $config -o lex.f2e.unsummed'
               , join=os.path.join(d.scriptdir,'join')
               , config=d.config_files 
               )
    hp.mapreduce( input='lex.f2e.unsummed'
                , mapper=os.path.join(bindir,'fields') + " 1 3 2 4"
                , sortkeys=2
                , reducer=os.path.join(d.scriptdir,'compose_table')
                , output='lex.final'
                )
    hp.remove('lex.f2estem')
    hp.remove('lex.f2estem.inverted')
    hp.remove('lex.estem2e')
hp.remove('lex.f2e.unsummed')
#hp.getmerge('lex.f2e.unsummed',os.path.join(d.tmpdir,'lex.unsummed.'+ext))
if not hp.file_exists('rules.alignments'):
    hp.mapreduce( input='rules'
                , output='rules.alignments'
                , mapper=os.path.join(d.config['variables']['rhbin'],'ifea')
                )
hp.mapreduce( input='lex.final' 
            , output='lex.final.flat' 
            , mapper=os.path.join(tdir,'rotate')
            , reducer=os.path.join(tdir,'flatten')
            , sortkeys=2
            )
#hp.getmerge('lex.final',os.path.join(d.tmpdir,'lex.final.'+ ext))
hp.remove('lex.final')
hp.mapreduce( input='rules.alignments'
            , mapper=os.path.join(tdir,'wordpairs') + flag
            , output='lex.wordpairs'
            )

hp.start(mappers=4)
cfg.execute(d,'$join lex.wordpairs lex.final.flat -c $config -e -E -k 3 -o lex.join',config=d.config_files,join=os.path.join(d.scriptdir,'join'))

hp.start(mappers=4,reducers=2)
hp.mapreduce( input='lex.join'
            , output='part.weightmorphlex.' + ext
            , mapper=os.path.join(tdir,'idfirst')
            , reducer=os.path.join(tdir,'score')+' -w 4 weightmorphlex.' + ext
            )
hp.remove('lex.join')
hp.start()
