#!/usr/bin/env python

import sys, collections

def pmap(mp):
    for k,v in mp.iteritems():
        print '%s\t%s' % (k,v)
    
mp = collections.defaultdict(int)
for line in sys.stdin:
    word,count = line.strip().split('\t')
    mp[word] += count
pmap(mp)

        
