#!/usr/bin/env python

import sys, collections

def pmap(mp):
    for k,v in mp.iteritems():
        print '%s\t%s' % (k,v)
    
mp = collections.defaultdict(int)
for line in sys.stdin:
    sig = line.split('\t')[0]
    vec = sig.split()
    for v in vec:
        if v[0] == '"' and v[-1] == '"' and len(v) >= 3:
            mp[v[1:-1]] += 1
    if len(mp) > 1000000:
        pmap(mp)
        mp = collections.iteritems()
pmap(mp)

        
            