#!/usr/bin/env python

import re, sys
leftparen = re.compile(r'\s*\(\s*')
rightparen = re.compile(r'\s*\)\s*')
sepkey = re.compile(r' -> .*$')
statetok = re.compile(r'[^\.]+\.([^\.]+)')
slottok = re.compile(r'x[0-9]+(:(\S*))?')
def key(str):
    str = sepkey.sub('',str)
    str = leftparen.sub('( ',str)
    str = rightparen.sub(' ) ',str)
    vec = str.split()
    stk = []
    key = []
    #print >> sys.stderr, vec
    for tok in vec:
        if tok[-1] == '(':
            tok = tok[:-1]
            tok = statetok.sub(r'\1',tok)
            stk.append(tok)
            key.append('"BEGINTAG(' + tok + ')"')
        elif tok[-1] == ')':
            key.append('"ENDTAG(' + stk.pop() + ')"')
        else:
            if slottok.match(tok):
                tok = slottok.sub(r'\2',tok)
                if tok != '':
                    key.append('"BEGINTAG(%s)"' % tok)
                    key.append('1')
                    key.append('"ENDTAG(%s)"' % tok)
            else:
                key.append('"%s"' % tok)
    return ' '.join(key)

for line in sys.stdin:
    line = line.strip()
    print '%s\t%s' % (key(line),line)
    
    