#!/usr/bin/env python

import sys

omitset = set((int(x.strip()) for x in open(sys.argv[1])))


for v in (line.rstrip('\n').split('\t') for line in sys.stdin):
    if int(v[0]) not in omitset:
        print '\t'.join(v)
