#!/usr/bin/env python

import sys, os

order = sys.argv[1]
greedy = sys.argv[2]
ngram = sys.argv[3].split(',')
narg = []

sys.stdout.write('--dlm-order %s ' % order)
sys.stdout.write('--greedy-dlm %s ' % greedy)
sys.stdout.write('--dependency-lm ')
for file in ngram:
    narg.append('big=%s' % os.path.abspath(file))
sys.stdout.write('%s\n' % ','.join(narg))
