#!/usr/bin/env python

import sys

occmap = {}
topn = int(sys.argv[1])

for line in sys.stdin:
    ignore,key,value = line.split()
    if key in occmap:
        occmap[key] += float(value)
    else:
        occmap[key] = float(value)

ret = []
for k,v in occmap.iteritems():
    ret.append((v,k))

ret.sort()
ret.reverse()

for v,k in ret[:topn]:
    print k


