#!/usr/bin/env perl
my %unesc=('^','^',
           '/',',',
           ';',':',
           '}',']',
           '{','[',
           '(','<',
           ')','>',
    );
while(<>) {
    s/\^(.)/exists $unesc{$1} ? $unesc{$1} : '^'.$1/ge;
    print;
}
