#!/usr/bin/perl

# Select a range of an alignment file:

my ($x1,$x2) = split(/-/,$ARGV[0],2);
my ($y1,$y2) = split(/-/,$ARGV[1],2);

while(<STDIN>) {
	foreach(split(/\s/)) {
	  my ($x,$y)=split /-/;
	  next if $x > $x2;
	  next if $y > $y2;
	  $x -= $x1;
	  $y -= $y1;
	  next if $x < 0;
	  next if $y < 0;
	  print "$x-$y ";
	}
}
print "\n"
