#!/usr/bin/env python

import sys

xsym = []
if len(sys.argv) > 1:
    for f in open(sys.argv[1]):
        if f[0] == 'X':
            xsym.append(f.strip())
else:
    xsym.append('X')


id = 3470020000
for s in sys.stdin:
  for w in s.split():
    if w != '<foreign-sentence>' and w != '</foreign-sentence>':
      for sym in xsym:
        print '%s(x0:%s) -> "%s" x0 ### maroon=10^-1 id=%s headmarker={{{R(H)}}}' % (sym,sym,w,id)
        id += 1

