#!/usr/bin/env python

import sys

y = 870000000001
unkstr = 'X(amr-unknown("/amr-unknown")) -> "%s" ### unknown=10^-1 id=%s'

for wd in sys.stdin:
    wdv = wd.split()
    for w in wdv:
        print unkstr % (w,y)
        y = y + 1
