#!/usr/bin/env python

import sys, re

okeeword = re.compile(r'^[a-zA-Z0-9_-]*$')
digi = re.compile('^-?[0-9.]*[0-9][0-9.]*$')

y = 870000000001
unkstr = '%s(Sxyz("/xyz")) -> "%s" ### unknown=10^-1 id=%s headmarker={{{R(H)}}}'
idstr = '%s(S%s("/%s")) -> "%s" ### identity=10^-1 id=%s headmarker={{{R(H)}}}'
nmstr = 'Aop("`%s`") -> "%s" ### generic-name=10^-1 id=%s headmarker={{{R(H)}}}'
aqstr = 'Aquant("%s") -> "%s" ### generic-quant=10^-1 id=%s headmarker={{{R(H)}}}' 

xsym = []
if len(sys.argv) > 1:
    for f in open(sys.argv[1]):
        if f[0] == 'X':
            xsym.append(f.strip())
else:
    xsym.append('X')



for wd in sys.stdin:
  wdv = wd.split()
  for w in wdv:
    if w != '<foreign-sentence>' and w != '</foreign-sentence>' and w not in set(['(',')','.','"','?',':',';']):
      for sym in xsym:
        if okeeword.match(w):
            print idstr % (sym,w,w,w,y)
        y += 1
      tg = w.replace("(","-lrb-").replace(")","-rrb-")
      print nmstr % (tg,w,y)
      y += 1
