#!/usr/bin/env python -u

import subprocess
import os
import os.path
import sys
import tempfile
print >> sys.stderr, 'starting:', ' '.join(sys.argv)
def repack(lst):
    return ' '.join('"%s"' % escaped for escaped in (s.replace('\\','\\\\').replace('"',r'\"') for s in lst))

cmdline = []
mapper = []
formapper = False
for tok in sys.argv:
    if tok == '--' and not formapper:
        formapper = True
        continue
    if formapper:
        mapper.append(tok)
    elif tok != '--':
        cmdline.append(tok)

cmd = repack(mapper)

print >> sys.stderr, 'execution of:', cmd
proc = subprocess.Popen( cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, shell=True)
tmpfile = None

while True:
    line = sys.stdin.readline()
    if line == '':
        break
    vline = line.rstrip('\n').split('\t')
    
    if tmpfile: 
        os.remove(tmpfile.name)
    tmpfile = tempfile.NamedTemporaryFile(delete=False)
    #print >> proc.stdin, sent
    proc.stdin.write(vline[0] + '\n')
    rule = ''
    while True:
        rule = proc.stdout.readline()
        if rule == '\n':
            tmpfile.close()
            print tmpfile.name
            break
        tmpfile.write(rule)
