#!/usr/bin/env perl

use FindBin qw($Bin);
use lib $Bin;
use NLPRules qw(extract_rhs_safe target_words source_words);

while (<>) {
    chomp;
    $rule = $_;
    foreach $f (source_words(extract_rhs_safe($rule))) {
	print "$f\n";
    }
}
