#!/usr/bin/env perl

#(graehl) create identity xrs rules given input tokenized foreign text.

use strict;
use warnings;
use Getopt::Long;
use File::Basename;
use IO::Handle qw( );

my $blobbase="/home/hpc-22/dmarcu/nlg/blobs";

### script info ##################################################
use FindBin;
use lib $FindBin::RealBin;
my $BLOBS;

BEGIN {
    $ENV{BLOBS}='/home/hpc-22/dmarcu/nlg/blobs' unless exists $ENV{BLOBS};
    $ENV{BLOBS}="$ENV{HOME}/blobs" unless -d $ENV{BLOBS};
    $BLOBS=$ENV{BLOBS};
    my $libgraehl="$BLOBS/libgraehl/v4";
    push @INC,$libgraehl if -d $libgraehl;
}

require "libgraehl.pl";
require "libxrs.pl";

### arguments ####################################################
my $BLOBS_TEMPLATE="{blobs}";

my $infile_name;
my $outfile_name;
my $fenc='raw';
my $tenc='raw';
my $CD='CD';
my $NN='NNP';
my $PUNC='SYM';
my $dopunc=0;
my $dotext=1;
my $donums=0;
my $baseid;
my $separator=0;

my $cls_punc=q(!-/:-@\[-`{-~);
my $cls_num=q{0-9.,\-:};
my $cls_alpha=q{a-zA-Z};
my $cls_text=$cls_alpha.$cls_num.$cls_punc;

my @opts_usage=("create identity xrs rules given input tokenized foreign text.",
                ["infile=s" => \$infile_name,"Take <file> as input (as well as the rest of ARGV)"],
                ["outfile=s" => \$outfile_name,"Write output here (can be .gz)"],
                ["foreign-encoding=s" => \$fenc, "Encoding used by (space separated) foreign words file"],
                ["target-encoding=s" => \$tenc, "Encoding for output"],
                ["do-numbers!" => \$donums,"Create rules for numbers"],
                ["number-pos=s" => \$CD, "Part of speech used for numbers"],
                ["do-text!" => \$dotext,"Create rules for words that are ASCII text"],
                ["text-pos=s" => \$NN, "Part of speech used except for numbers"],
                ["do-punc!" => \$dopunc, "Create rules for punctuation"],
                ["punc-pos=s" => \$PUNC, "Default part of speech used for purely-punctuation words (Note: single-character punctuation is handled specially, e.g. '('->-LRB- '\"'->'')"],
                ["xrs-baseid=i" => \$baseid, "If set, start rule id=N here, increasing in distance from 0"],
                ["separator!" => \$separator, "empty newline separator"],
               );

my $cmdline=&escaped_cmdline;
my ($usagep,@opts)=getoptions_usage(@opts_usage);

info("COMMAND LINE:");
info($cmdline);
show_opts(@opts);

expand_opts(\@opts_usage,[$BLOBS_TEMPLATE,$BLOBS]);


### main program ################################################
my $enc=set_inenc($fenc);
use open IN => $enc;

if ($infile_name) {
    info("Adding infile = $infile_name");
    unshift @ARGV,$infile_name;
}
outz_stdout($outfile_name);
set_outenc($tenc);

my %rules;

sub create_rule
{
    my ($a,$b,$c) = @_;
    $rules{&xrs_lexical_rule($a,$b)}=$c;
}

my $inc=(defined $baseid && $baseid < 0) ? -1 : 1;

while (<>) {
    chomp;
    my @words=split;
    for (@words) {
        if (/^[$cls_punc]*$/) {
            my $puncpos=punc_pos($_);
            $puncpos=$PUNC unless defined $puncpos;
            info_remember_quiet("punctuation",": $puncpos($_)");
            create_rule($puncpos,$_,"punc") if $dopunc;
        } elsif (/^[$cls_num]*$/) {
            info_remember_quiet("number",": $CD($_)");
            create_rule($CD,$_,"num") if $donums;
        } elsif (/^[$cls_text]*$/) {
            info_remember_quiet("text",": $NN($_)");
            create_rule($NN,$_,"ansi") if $dotext;
        } else {
            info_remember_quiet("foreign",": $_");
        }
    }
    for (sort keys %rules) {
        unless (/"<foreign-sentence>"/ || "/"</foreign-sentence>"/) {
            my $r = $_;
            print $r;
            if ($baseid) {
                print " id=$baseid";
                $baseid+=$inc;
            }
            my $a = $rules{$r};
            print " identity=1 identity-$a=1";
            print "\n";
        }
    }
    if ($separator) { print "\n"; }
    STDOUT->flush();
    %rules = ();
}





&info_summary;
