#!/usr/bin/env python
import sys, os, re
offset = 0
newoffset = 0
linevec = []

idmatch = re.compile('#([0-9]+)([ (])')

def idsub(m):
    global newoffset
    global offset
    x = int(m.group(1)) + offset
    newoffset = max(x,newoffset)
    return '#' + str(x) + m.group(2) 


def printjoin(lv):
    global newoffset
    global offset
    if len(lv) == 0:
        pass
    elif len(lv) == 1:
        print lv[0]
    else:
        offset = 1
        newoffset = 1
        print '#1(111111111111<>',
        for vv in lv:
            print idmatch.sub(idsub,vv),
            offset = newoffset + 1
            newoffset += 1
        print ')'
        sys.stdout.flush()

while True:
    line = sys.stdin.readline()
    if line == '':
        printjoin(linevec)
        break
    line = line.strip()
    if line == '':
        printjoin(linevec)
        linevec = []
    else:
        linevec.append(line)

        
