#!/usr/bin/env python

import sys, os

sentmarks = set(['.','?','!'])
subsentmarks = set(['.','?','!',',',';',':'])

maxlen = int(sys.argv[1])

def setsplit(line,aset):
   vvout = []
   for vv in line.split():
      vvout.append(vv)
      if vv[0] in aset or vv[-1] in aset:
         yield vvout
         vvout = []
   if len(vvout):
      yield vvout

def linesplit(line,mlen):
   vvout = []
   for vv in line.split():
      if len(vvout) >= mlen/2 - 1:
         yield vvout
         vvout = []
      vvout.append(vv)
   if len(vvout):
      yield vvout
          
while True:
   line = sys.stdin.readline()
   if line == '':
      break
   vline = line.split()
   if len(vline) < maxlen:
      print ' '.join(vline)
   else:
      vvline = list(setsplit(line,sentmarks))
      k = True
      for vv in vvline:
         if len(vv) >= maxlen:
            k = False
      if k:
         for vv in vvline:
            print ' '.join(vv)
      else:
         vvline = list(setsplit(line,subsentmarks))
         k = True
         for vv in vvline:
            if len(vv) >= maxlen:
               k = False 
         if k:	 
            for vv in vvline:
               print ' '.join(vv)
         else:
            vvline = list(linesplit(line,maxlen))
            for vv in vvline:
               print ' '.join(vv)
   print
   sys.stdout.flush()
