#!/usr/bin/env python
import re, sys

mrk = 'lineNumber'
if len(sys.argv) > 2:
    mrk = sys.argv[2]
lineno = re.compile(r'\b%s=(\d+)' % mrk)
offset = int(sys.argv[1])

def replace(mtch):
    return mrk + '=' + str(int(mtch.group(1)) + offset)

def repair(line):
    return lineno.sub(replace,line)

for line in sys.stdin:
    sys.stdout.write(repair(line))

