#!/usr/bin/env python

import subprocess, os, sys, re

digit = re.compile(r'\d+')

dictionary = set((v.strip() for v in open(sys.argv[1])))
sys.stderr.write("segmentation command: %s\n" % ' '.join(('"%s"' % w for w in sys.argv[2:])))
morfessor = subprocess.Popen(' '.join(sys.argv[2:]),shell=True,stdin=subprocess.PIPE,stdout=subprocess.PIPE)

sentence_boundaries = set(['<foreign-sentence>', '</foreign-sentence>'])
escs = set(['"','\\'])

def cstr(s):
    news = ''
    for ss in s:
        if ss in escs:
            news += '\\'
        news += ss
    return news
n = 1
while True:
    line = sys.stdin.readline()
    if line == '':
        break
    line = line.strip()
    if line == '':
        continue
    vline = line.split()
    x = 0
    for v in vline:
        if v not in sentence_boundaries:
            morfessor.stdin.write(v + ' ')
    morfessor.stdin.write('\n')
    print 'lattice id="%s" {' % n,
    for v in vline:
        if v in sentence_boundaries:
            print '[%s,%s] "%s";' % (x,x+1,cstr(v)),
            x += 1
        else:
            indict = (digit.sub('@',v) in dictionary)
            oldx = x
            vmv = morfessor.stdout.readline().strip().split()
            if len(vmv) > 10 or (len(v) > 2 and v[0:2] == '@@'):
                vmv = [ v ]
            if len(vmv) > 1:
                for vm in vmv:
                    print '[%s,%s] "%s" morf-token="10^-1" ' % (x,x+1,cstr(vm)),
                    if indict:
                        print 'morf-in-dict="10^-1" ',
                    print ';',
                    x += 1
                print '[%s,%s] "%s" orig-token="10^-1" ' % (oldx,x,cstr(v)),
                if indict:
                    print 'orig-in-dict="10^-1" ',
                print ';',
            else:
                if len(v) > 2 and v[0:2] == '@@':
                    print '[%s,%s] "%s" orig-token="10^-1" morf-token="10^-1" ignore-dnt="10^-1" ; ' % (x,x+1,cstr(v[2:])),
                print '[%s,%s] "%s" orig-token="10^-1" morf-token="10^-1" ' % (x,x+1,cstr(v)),
                if indict:
                    print 'morf-in-dict="10^-1" orig-in-dict="10^-1" ',
                print ';',
                x += 1
    print '};'
    sys.stdout.flush()
    n += 1
morfessor.stdin.close()
            
