#!/usr/bin/env python
import os, sys, subprocess, string, re
k = int(os.getenv('mapred_task_partition','0'))
k = '%06d' % k
cmd = ' '.join(sys.argv[1:])
cmd = re.sub(r'%k\b','%(k)s',cmd)
cmd = cmd % { 'k': k }

print >> sys.stderr, "command:", cmd
cmd = subprocess.Popen(cmd, shell=True, stdin=subprocess.PIPE)

for line in sys.stdin:
    id,nb,data = line.split('\t')
    cmd.stdin.write(data)
cmd.stdin.close()
cmd.wait()

#cmd = '$latvizprep --global $globalgram --grammar-view $grammar_view --per-sentence $tmpdir --output $tmpdir/viz-$k.txt --index $tmpdir/viz-$k.idx 
