#!/usr/bin/env python

import sys

def splits(seq):
    m = {}
    for p in seq:
        v = p.split()
        m[v[0]] = v[1:]
    return m

fh = open(sys.argv[1])
m = splits(fh)

for nts in sys.stdin:
    for nt in nts.split():
        if nt in m:
            for s in m[nt]:
                print s

        else:
            print nt
