#!/usr/bin/env python
import sys
import argparse
parser = argparse.ArgumentParser(description="select 0-based fields in mapper context")
parser.add_argument("--infile", "-i", nargs='?', type=argparse.FileType('r'), default=sys.stdin, help="input file")
parser.add_argument("--outfile", "-o", nargs='?', type=argparse.FileType('w'), default=sys.stdout, help="output file")
parser.add_argument("--fields", "-f", nargs='+', help="space-separated list of fields to keep, in the order preferred")

args = parser.parse_args()

try:
    args = parser.parse_args()
except IOError, msg:
    parser.error(str(msg))

fields = map(int, args.fields)
for line in args.infile:
    ifields=line.rstrip('\n').split('\t')
    ofields=[ifields[x] for x in fields]
    args.outfile.write('\t'.join(ofields)+'\n')
