#!/usr/bin/env python
import sys

for tgt,src in (line.rstrip('\n').split('\t') for line in sys.stdin):
    tgtv = tgt.decode('utf-8').split()
    src = src.decode('utf-8').lower()
    newtgtv = []
    curr = ''
    for t in tgtv:
        if len(curr) == 0:
            curr = t
        elif src.find(curr.lower()) < 0:
            newtgtv.append(curr)
            curr = t
        elif src.find((curr+t).lower()) < 0:
            newtgtv.append(curr)
            curr = t
        else:
            curr = curr + t
    if len(curr) > 0:
        newtgtv.append(curr)
    sys.stdout.write(' '.join(newtgtv).encode('utf-8') + '\n')
    sys.stdout.flush()
