#!/usr/bin/env python

import sys, itertools

def keyval(input):
    for line in input:
        m = {}
        k,v = line.split('\t')
        for vv in v.split():
            kl,vl = vv.split('=')
            m[int(kl)] = int(vl)
        yield k,m

# input:  
#     sequence of:
#         key \t length1=val1 length2=val2 ...
# output: 
#     key \t length1 \t count2
#     ... \t ...     \t ...
#     key \t lengthN \t countN



def reducer(input):
    for key, records in itertools.groupby(keyval(input), lambda x: x[0]):
        counts={}
        for k,m in records:
            for kl,vl in m.iteritems():
                if kl in counts:
                    counts[kl] += vl
                else:
                    counts[kl] = vl
        
        yield key, counts


if __name__ == "__main__":
    for key, counts in reducer(sys.stdin):
        ckeys = counts.keys()
        ckeys.sort()
        print key + '\t' + ' '.join('%s=%s' % (c,counts[c]) for c in ckeys)
