#!/usr/bin/env python
import sys

for line in sys.stdin:
    vec = [x.strip() for x in line.rstrip('\n').split('\t')]
    etree,fsent,align = vec[:3]
    if etree == '' or etree == '0' or align == '':
        continue
    print '\t'.join(vec)
    
